export const ProductPageLocators = {
  settingIcon: '#react-burger-menu-btn',
  logoutLink: '#logout_sidebar_link',
  aboutLink: '#about_sidebar_link',
  requestDemoButton: 'a[href="/request-demo"]:visible',
  try_it_free: 'button:has-text("Try it free")',
  productNames: '.inventory_item_name',
  productDesc: '.inventory_item_desc',
  productPrices: '.inventory_item_price',
  addToCartButtons: '.btn.btn_small.btn_inventory',
  filterDropdown: '.product_sort_container',
  filterByNameAtoZ: 'option[value="az"]',
  filterByNameZtoA: 'option[value="za"]',
  filterByPriceLtoH: 'option[value="lohi"]',
  filterByPriceHtoL: 'option[value="hilo"]',
  cartLink: '.shopping_cart_link',
};
